FROM python:3.7-slim AS server

RUN mkdir /server
WORKDIR /server

RUN pwd
RUN ls -la
COPY ../../requirements.txt /server/
RUN pip install -r requirements.txt

COPY ../../ /server
RUN python ./manage.py collectstatic --noinput
