pipeline {
    agent {
    dockerfile {
        filename 'server/Dockerfile'
    }
}
    stages {
        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'pytest'
            }
        }
    }
}