pipeline {
    agent {
        docker { image 'python:3.7-slim' }
    }
    stages {
        stage('Build') {
            steps {
                sh 'python -V'
                sh 'ls -la'
                sh 'pwd'
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                sh 'pytest'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}